meerket/meerket-domain/build.gradle, meerket/meerket-domain/src/main/java/org/j1p5/domain/auth/area/entity/AreaAuthEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/auth/area/repository/AreaAuthRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/block/entity/BlockEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/block/repository/BlockRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/history/search/entity/SearchHistory.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/history/search/repository/SearchHistoryRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/report/entity/ReportEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/report/entity/ReportTarget.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/report/repository/ReportRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/ActivityArea.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/SearchHistory.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/ActivityArea.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/EmdArea.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/Provider.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/Role.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/SearchHistory.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/SggArea.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/SidoArea.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/UserEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/ActivityAreaRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/EmdAreaRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/SearchHistoryRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/UserRepository.java
유저, 차단, 신고 도메인 관련 엔티티, 레포지토리 초기 설정
=> init : user block report init

meerket/meerket-application/src/main/java/org/j1p5/api/global/config/SwaggerConfig.java
#9 스웨거 설정
<br/>
- 서비스에 맞게 스웨거 ui에 나타나는 기본 정보 수정했습니다.
<br/>
=> swagger 정보를 설정한다.

meerket/meerket-application/src/main/java/org/j1p5/api/auth/api/OauthController.java
#14 로그아웃 기능 구현
<br/>
- 로그아웃 기능 구현
<br/>
- 간단한 세션 무효화입니다.
<br/>
<br/>
=> feat : 로그아웃 기능 구현

meerket/build.gradle, meerket/meerket-application/src/main/java/org/j1p5/api/global/excpetion/WebErrorCode.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/converter/MultipartFileConverter.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/controller/UserController.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/dto/ImageRegisterRequest.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/dto/NameRegisterRequest.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/exception/NicknameAlreadyExistException.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/exception/UserNotFoundException.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/service/UserRegisterService.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/usecase/UserImageRegisterUsecase.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/usecase/UserNameRegisterUsecase.java, meerket/meerket-application/src/main/resources/application.yml, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/UserImageClient.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/EmdArea.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/UserEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/UserRepository.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageServiceImpl.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/S3Config.java, meerket/meerket-infrastructure/src/main/resources/application-infrastructure.yml
#16 
<br/>
- 로그인 이후 이미지와 닉네임을 설정하는 기능 구현
<br/>
- 이미지 등록 관련 로직은 성현님께서 작성해주신 클래스 내부에 작성했습니다.
<br/>
1. 계층별로 exception을 나누었는데, crud로 인해 나는 오류는 api exception이라 하는게 맞을까요? 현재는 api 모듈 속 exception이 web exception이라 네이밍되어 있습니다.
2. 현재 service 클래스에 crud를 포함시켜놓았습니다. 이러다보니 흐름이 아닌 구현체 클래스에 crud를 포함시키게 되었는데요. 만약 crud를 usecase에 놓는다고 했을 때, transactional 크기의 문제는 없을까요?
3. 현재 저희가 흐름을 usecase, 구현을 service 클래스에 작성했습니다. 이렇게 컨벤션을 정해서 작성하여 service클래스에만 repository에 접근하도록 하고 있습니다. 성현님 pr리뷰를 보고 간단한 crud나 로직들은 service로 접근할 필요없이 usecase에서 처리하면 된다고 이해했는데, 저희가 정한 컨벤션이 적절한 것인지 궁금합니다!
=> Feat/#16 register nickname, image

meerket/meerket-application/src/main/java/org/j1p5/api/comment/controller/CommentController.java, meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/request/CommentCreateRequestDto.java, meerket/meerket-application/src/main/java/org/j1p5/api/comment/exception/CommentErrorCode.java, meerket/meerket-application/src/main/java/org/j1p5/api/comment/service/CommentService.java, meerket/meerket-application/src/main/java/org/j1p5/api/comment/usecase/CommentCreateUsecase.java, meerket/meerket-application/src/main/java/org/j1p5/api/global/config/SecurityConfig.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/entity/CommentEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
<br/> #37 
<br/> 게시물에 댓글을 생성하는 잡업
<br/> 
- 스웨거 설정은 다음 PR부터 하겠습니다!
<br/>
- Controller -> Usecase -> service 흐름을 처음 구현 적용해봐서 잘 구현되었는지 피드백해주시면 감사하겠습니다!
- 대댓글 구현을 위해 self-join을 구현해보았는데 한번 봐주시면 감사하겠습니다!
=> [Feat] 댓글을 생성한다

meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductResponseInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/exception/ProductException.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustom.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductUserReader.java
<br/> #51 
<br/> 카테고리 기반조회
<br/> 편하게 봐주세요!
<br/>
=> [Feat] : 카테고리 기반으로 상품을 조회할 수 있다

meerket/build.gradle, meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/controller/ActivityAreaController.java, meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/dto/AllAreaResponse.java, meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/service/ActivityAreaService.java, meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/usecase/ActivityAreaUsecase.java, meerket/meerket-common/src/main/java/org/j1p5/common/dto/PageResult.java, meerket/meerket-domain/build.gradle, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/dto/ActivityAreaAddress.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/dto/ActivityAreaFullAddress.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/ActivityAreaRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/querydsl/ActivityAreaRepositoryCustom.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/querydsl/ActivityAreaRepositoryCustomImpl.java
#48 
<br/>
- 활동 지역 조회 기능 구현했습니다.
<br/>
<br/>
<br/>
=> [Feat] : 사용자는 근처 지역을 조회할 수 있다

meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/service/ActivityAreaService.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/AuthManager.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/api/OauthController.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/dto/LoginResponse.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/dto/SessionInfo.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthLoginUsecase.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthService.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/ActivityAreaRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/UserInfo.java
#64 
<br/>
- 로그인 시 유저 이름, 프로필 사진, 활동지역 응답 프로퍼티 추가
<br/>
<br/>
<br/>
=> [Refactor] : 로그인 로직 리팩터링

meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/controller/ActivityAreaController.java, meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/service/ActivityAreaService.java, meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/usecase/ActivityAreaReadUsecase.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/querydsl/ActivityAreaRepositoryCustom.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/querydsl/ActivityAreaRepositoryCustomImpl.java
#67 
<br/>
- 검색어로 동네 검색 기능 구현
<br/>
- 우선 like검색으로 구현. 추후 기능 고도화
<br/>
<br/>
=> [Feat] : 검색어 기반 동네 검색

meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatRoomService.java, meerket/meerket-application/src/main/java/org/j1p5/api/comment/service/CommentService.java, meerket/meerket-application/src/main/java/org/j1p5/api/global/converter/PointConverter.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/converter/PointConverter.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/request/ProductCreateRequestDto.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/request/ProductUpdateRequest.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/response/CreateProductResponseDto.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/response/MyProductResponseDto.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/exception/ProductException.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ActivityAreaReader.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/EmdNameReader.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductAppender.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductService.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductUserReader.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/RegionAuthHandler.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/UserLocationNameReader.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductResponseInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductUpdateInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustom.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageServiceImpl.java
=> [Refactor] : Product 리팩토링

meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/exception/ProductException.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductService.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustom.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
<br/> #75 
<br/>키워드로 상품조회기능 구현
<br/> 100km이내의 상품들만 조회되는건 유지됨
<br/>
=> keyword로 상품을 조회할 수 있다

meerket/meerket-application/src/main/java/org/j1p5/api/areaAuth/controller/AreaAuthController.java, meerket/meerket-application/src/main/java/org/j1p5/api/areaAuth/dto/AuthAreaRequest.java, meerket/meerket-application/src/main/java/org/j1p5/api/areaAuth/exception/AreaAuthNotFoundException.java, meerket/meerket-application/src/main/java/org/j1p5/api/areaAuth/exception/PointNotMatchException.java, meerket/meerket-application/src/main/java/org/j1p5/api/areaAuth/service/AreaAuthService.java, meerket/meerket-application/src/main/java/org/j1p5/api/areaAuth/usecase/AreaAuthUsecase.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthLoginUsecase.java, meerket/meerket-application/src/main/java/org/j1p5/api/global/converter/PointConverter.java, meerket/meerket-application/src/main/java/org/j1p5/api/global/excpetion/WebErrorCode.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/RegionAuthHandler.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/controller/UserController.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/areaAuth/entity/AreaAuthEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/areaAuth/repository/AreaAuthRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/areaAuth/repository/EmdAreaRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/areaAuth/vo/AreaAuthInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/custom/EmdAreaRepositoryCustom.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/custom/EmdAreaRepositoryCustomImpl.java
#77
<br/>
- 위치 기반 인증 구현
- 좌표 값이 emdId로 들어온 읍면동 지역의 polygon 내부에 있는지 판단
<br/>
<br/>
<br/>
=> [Feat] 사용자는 위치 기반 지역 인증을 할 수 있다.

meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/response/CloseEarlyResponseDto.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/exception/ProductException.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductService.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductResponseDetailInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java
<br/> #79 
<br/>이슈확인해 주세요!
<br/>
<br/>
=> [Feat] : 조기마감 구현

meerket/meerket-application/src/main/java/org/j1p5/api/global/config/CorsConfig.java, meerket/meerket-application/src/main/resources/application.yml
- 쿠키 samsite none으로 변경
- cors 주소 추가
<br/>
<br/>
<br/>
<br/>
=> [hotfix] : 프론트 연계 cors, 세션 쿠키 설정 변경

meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/controller/ActivityAreaController.java
#90 
<br/>
- 컨트롤러 매핑 오류 수정
<br/>
<br/>
<br/>
=> [Hotfix] : mapping 어노테이션 수정

meerket/meerket-application/src/main/java/org/j1p5/api/global/config/OctetStreamMsgConverter.java, meerket/meerket-application/src/main/java/org/j1p5/api/global/config/SwaggerConfig.java, meerket/meerket-application/src/main/java/org/j1p5/api/global/config/WebConfig.java
#95 
<br/>
- octet-stream 허용해주는 컨버터 생성
- 스웨거에서 로컬 서버 추가
<br/>
<br/>
<br/>
=> [Hotfix] : json과 file 함께 들어오지 않는 버그 픽스

meerket/meerket-application/src/main/java/org/j1p5/api/auth/dto/LoginResponse.java
#97 
<br/>
- 로그인 response에서 활동지역이 null이라면 해당 프로퍼티 null로 반환.
<br/>
<br/>
<br/>
=> fix : 회원가입 시 500에러 반환 오류 수정

meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/querydsl/ActivityAreaRepositoryCustomImpl.java
#99 
<br/>
- fetch join과 where절 동시 사용으로 인한 에러 해결
- user와 활동지역 조인
<br/>
<br/>
<br/>
=> [Hotfix] : 유저 조회 에러 해결

meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/service/ActivityAreaService.java, meerket/meerket-application/src/main/java/org/j1p5/api/global/config/SwaggerConfig.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/ActivityAreaRepository.java
#102 
<br/>
- 유저 활동 지역 조회 시 유저+들어온 emdId기반이 아닌 유저 기반으로 조회
- 스웨거 로컬 및 운영환경 추가
<br/>
<br/>
<br/>
=> [Fix] : 활동 지역 수정 404에러

meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatMessageService.java, meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatRoomService.java, meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/EnterChatRoomUseCase.java, meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/ExitChatRoomUseCase.java, meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/GetUserChatRoomsUseCase.java, meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/SendChatMessageUseCase.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/ChatMessageRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/ChatRoomRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatMessageCustomRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatMessageCustomRepositoryImpl.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatRoomCustomRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatRoomCustomRepositoryImpl.java
<br/> #93 
<br/> 채팅 도메인에 customRepository를 적용하는 리팩토링을 진행했습니다.
멘토님 피드백을 반영해서 하나의 useCase에서만 사용되는 fit한 메서드들은 service에 두지 않고 useCase 에 private로 선언하였습니다
=> refactor : ChatCustomRepository 생성하여 리팩토링

meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/command/UpdateChatRoomCommand.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/exception/ChatDomainException.java
=> fix : command 추가

meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/usecase/PlaceBidUseCase.java, meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/SendChatMessageUseCase.java, meerket/meerket-application/src/main/java/org/j1p5/api/fcm/FcmService.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/request/ProductCreateRequestDto.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductService.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/auction/repository/AuctionRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/fcm/FcmSender.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/fcm/repository/FcmTokenRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductLocationInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductResponseDetailInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/FcmSenderImpl.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/exception/FcmException.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageValidator.java
=> [Feat] fcm알림구현

meerket/meerket-application/src/main/java/org/j1p5/api/user/controller/UserController.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/usecase/UserProfileReadUsecase.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/UserProfile.java
#104 
<br/>
- 임시로 유저 프로필 확인 및 권한 부여를 위해 api 구현
<br/>
<br/>
<br/>
=> [Feat] : 임시 유저 세션용 api 구현

meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductResponseDetailInfo.java
=> refactor : auction null허용

meerket/meerket-application/src/main/java/org/j1p5/api/product/exception/ProductException.java
#118 
<br/>
- 상품 삭제 시 입찰자 오류 코드 4자리 3자리로 수정
<br/>
<br/>
<br/>
=> [Hotfix] : 상품 삭제 시 입찰자 오류 발생 픽스

meerket/meerket-application/src/main/java/org/j1p5/api/block/controller/BlockController.java, meerket/meerket-application/src/main/java/org/j1p5/api/block/dto/BlockRegisterRequest.java
=> [refactor] 차단 등록 요청 프로퍼티 네이밍 수정

meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthService.java, meerket/meerket-application/src/test/java/org/j1p5/api/auth/AuthFixture.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/auth/dto/OauthProfile.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/UserEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/UserRepository.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/service/UserAppender.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/user/service/UserReader.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/kakao/dto/KakaoProfile.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/naver/dto/NaverProfile.java
#134 
<br/>
- 소셜 로그인 시 반려 사유로 인해 이메일 수집 안하도록 수정
<br/>
<br/>
<br/>
=> [refactor]  소셜 로그인 시 이메일 수집 안하도록 수정

meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/CommentMemeberDto.java, meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/response/CommentReadResponseDto.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/CommentInfo.java
=> [refactor] : 차단 기능 동작을 위해 댓글 조회에 유저 id추가

meerket/meerket-application/src/main/java/org/j1p5/api/comment/exception/CommentNotFoundException.java, meerket/meerket-application/src/main/java/org/j1p5/api/product/exception/ProductNotFoundException.java, meerket/meerket-application/src/main/java/org/j1p5/api/report/controller/ReportController.java, meerket/meerket-application/src/main/java/org/j1p5/api/report/dto/ReportRegisterRequest.java, meerket/meerket-application/src/main/java/org/j1p5/api/report/service/ReportRegisterService.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/global/exception/DomainErrorCode.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/report/ReportImageClient.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/report/ReportInfo.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/report/entity/ReportEntity.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/report/entity/ReportType.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageServiceImpl.java
#137 
<br/>
- 상품, 댓글 사용자에 대한 신고 등록
- 현재 이미지 요청은 가능하지만 테이블에 저장되진 않는 상태입니다.
<br/>
- 이미지 테이블에 관한 논의가 필요할 것 같습니다. 도메인별 이미지 테이블을 둘지, 하나로 통합할지, 공통 이미지 컬럼을 두고 서브 테이블로 도메인 별 이미지 테이블을 둘지 결정해야할 것 같아요.
<br/>
<br/>
=> [Feat] 신고 등록

meerket/meerket-domain/src/main/java/org/j1p5/domain/auction/repository/AuctionRepository.java
=> fix : 컬럼 오기입 수정

meerket/meerket-application/src/main/java/org/j1p5/api/auth/api/OauthController.java, meerket/meerket-application/src/main/java/org/j1p5/api/report/controller/ReportController.java, meerket/meerket-application/src/main/java/org/j1p5/api/user/controller/UserController.java
#143 
<br/>
- 로그인 이슈는 디비에 컬럼 만들지 않았던 문제.
- 신고 타입, 로그인 타입 관련 설명이 없어 스웨거에 명시
- 회원 탈퇴 api delete mapping으로 수정
<br/>
<br/>
<br/>
=> [Hotfix] 로그인 에러 수정

meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
=> [Hotfix] : 상품 조회 query 에러 수정

meerket/meerket-application/src/main/java/org/j1p5/api/auth/api/OauthController.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/dto/LoginRequest.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthService.java, meerket/meerket-application/src/main/java/org/j1p5/api/auth/usecase/OauthLoginUsecase.java
=> feat : fcm 토큰 저장 기능 추가

meerket/meerket-application/src/main/java/org/j1p5/api/global/config/CorsConfig.java
=> feat : cors domain 추가

meerket/meerket-application/src/main/java/org/j1p5/api/fcm/FcmRedirectUri.java, meerket/meerket-application/src/main/java/org/j1p5/api/fcm/FcmService.java, meerket/meerket-domain/src/main/java/org/j1p5/domain/fcm/FcmSender.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/FcmSenderImpl.java
#170 
<br/>
- 푸시 알림 시 redirect할 수 있는 uri를 제공했습니다.
<br/>
<br/>
<br/>
=> 푸시 알림 시 data삭제, uri 추가

meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/FcmSenderImpl.java
=> refactor : fcm notification 제거

.github/workflows/cd-prod.yml
=> HOTFIX : cicd 오류 수정

.github/workflows/cd-prod.yml
=> fix : bucket name 변경

meerket/meerket-application/src/main/java/org/j1p5/api/global/config/SwaggerConfig.java
=> refactor : 운영 서버 url 수정

meerket/meerket-application/src/test/java/org/j1p5/api/auction/fixture/AuctionFixture.java, meerket/meerket-application/src/test/java/org/j1p5/api/auction/fixture/ProductFixture.java, meerket/meerket-application/src/test/java/org/j1p5/api/auction/fixture/UserFixture.java, meerket/meerket-application/src/test/java/org/j1p5/api/auction/service/AuctionServiceTest.java, meerket/meerket-application/src/test/java/org/j1p5/api/user/UserFixture.java
<br/> AuctionService에 대한 테스트 코드를 작성했습니다.
<br/> 테스트 코드 작성이 익숙치가 않아서 제대로 쓴건지 모르겠습니다!
중간에 EmdNameReader에 있는 getEmdName 메서드가 정적 메서드라서 mockito에 있는 정적 메서드 모킹 기능으로 테스트를 작성하기는 했는데 아래 링크에서 보면 정적메서드 모킹이 안티 패턴이라는 말이 있더라구요! 그냥 공유하고 싶어서 첨부했습니다. 
또 테스트마다 몇개는 fixture를 쓰고, 몇개는 mock()으로 간단히 생성해서 테스트 작성했습니다.
그리고 UserFixture가 이미 하나 생성되어있었는데 해당 클래스에 create() 메서드 파라미터가 제대로 들어있지않아 동작이 안되어서 
그부분도 수정했습니다!
참고
https://velog.io/@betterfuture4/Static-%EB%A9%94%EC%86%8C%EB%93%9C%EB%A5%BC-mocking%ED%95%98%EC%A7%80-%EB%A7%90%EC%9E%90-feat.-LocalDate.nowclock 
https://wonit.tistory.com/631
=> test : AuctionService에 대한 테스트 코드 작성

meerket/meerket-application/src/main/java/org/j1p5/api/fcm/FcmService.java, meerket/meerket-application/src/main/java/org/j1p5/api/fcm/type/FcmMessageType.java, meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/FcmSenderImpl.java
#170 
<br/>
- fcm type 초기화 오류 수정
- 채팅 시 내용도 함께 전송
<br/>
<br/>
<br/>
=> fix : fcm type 초기화 오류 수정

meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/FcmSenderImpl.java
#182 
<br/>
- Fcm 구조 수정
- Notification 구조 대신 Map 사용하여 data에 일괄 삽입
<br/>
<br/>
<br/>
=> refactor : fcm 구조 수정
